<HR NOSHADE SIZE=3>
<font color=#FF9D6E>3월 : 완성의 부대는 공격해 들어오는 공도의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#FF9D6E>3월 : 고구려국의 공도부대는 완성에 쳐들어갔습니다!</font>
<font color=#FF9D6E>3월 : 완성의 수비대가 농성을 준비하고 있는 듯 하다! 공도의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#41A541>10월 : 소패성의 부대는 공격해 들어오는 황개의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#41A541>10월 : 촉국의 황개부대는 소패성에 쳐들어갔습니다!</font>
<font color=#41A541>10월 : 소패성의 수비대가 농성을 준비하고 있는 듯 하다! 황개의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#FF9D6E>12월 : 하비성의 부대는 공격해 들어오는 여령기의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#FF9D6E>12월 : 고구려국의 여령기부대는 하비성에 쳐들어갔습니다!</font>
<font color=#FF9D6E>12월 : 하비성의 수비대가 농성을 준비하고 있는 듯 하다! 여령기의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>12월 : 타사대왕의 부대가 천수성을 점령했다!</font>
<font color=#D064D0>12월 : 초국의 타사대왕부대는 천수성에 쳐들어갔습니다!</font>
<font color=#D064D0>12월 : 천수성의 수비대가 농성을 준비하고 있는 듯 하다! 타사대왕의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>11월 : 천수성의 부대는 공격해 들어오는 장료의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>11월 : 초국의 장료부대는 천수성에 쳐들어갔습니다!</font>
<font color=#D064D0>11월 : 천수성의 수비대가 농성을 준비하고 있는 듯 하다! 장료의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>10월 : 천수성의 부대는 공격해 들어오는 이통의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>10월 : 초국의 이통부대는 천수성에 쳐들어갔습니다!</font>
<font color=#D064D0>10월 : 천수성의 수비대가 농성을 준비하고 있는 듯 하다! 이통의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>9월 : 천수성의 부대는 공격해 들어오는 태사향의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>9월 : 초국의 태사향부대는 천수성에 쳐들어갔습니다!</font>
<font color=#D064D0>9월 : 천수성의 수비대가 농성을 준비하고 있는 듯 하다! 태사향의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#FF9D6E>3월 : 여령기의 부대는 요격중이던 장합의 부대를 파죽지세로 전멸시킨 모양이다.</font>
<table border=1 width=274 align=center><tr><td width=100 bgcolor=#FF9D6E><p align=center><img src=./image/284.gif></p></td><td width=52 height=171 rowspan=3 bgcolor=black><p align=center><b><font color=white>VS</font></b></p></td><td width=100 bgcolor=#41A541><p align=center><img src=./image/453.gif></p></td></tr><tr><td width=100 height=19 bgcolor=#FF9D6E><p align=center><b>여령기<br></b></td><td width=100 height=19 bgcolor=#41A541><p align=center><b>장합</b></td></tr><tr><td width=100 height=102 bgcolor=black><p><b>총전투력:0</b><br>병종:보병<br>훈련도:59<br>지형상성:100</td><td width=100 height=102  bgcolor=black><b>총전투력:23</b><br>병종:보병<br>훈련도:100<br>지형상성:100</td></tr></table>
<font color=#FF9D6E>3월 : 고구려국의 여령기부대는 하비성에 쳐들어갔습니다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>3월 : 장료의 부대가 서량성을 점령했다!</font>
<font color=#D064D0>3월 : 초국의 장료부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>3월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 장료의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>2월 : 서량성의 부대는 공격해 들어오는 타사대왕의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>2월 : 초국의 타사대왕부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>2월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 타사대왕의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>1월 : 서량성의 부대는 공격해 들어오는 화핵의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>1월 : 초국의 화핵부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>1월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 화핵의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>1월 : 서량성의 부대는 공격해 들어오는 손수의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>1월 : 초국의 손수부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>1월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 손수의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>1월 : 서량성의 부대는 공격해 들어오는 조민의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>1월 : 초국의 조민부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>1월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 조민의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>12월 : 서량성의 부대는 공격해 들어오는 문추의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>12월 : 초국의 문추부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>12월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 문추의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>12월 : 서량성의 부대는 공격해 들어오는 유봉의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>12월 : 초국의 유봉부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>12월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 유봉의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>11월 : 서량성의 부대는 공격해 들어오는 이사부의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>11월 : 초국의 이사부부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>11월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 이사부의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>11월 : 서량성의 부대는 공격해 들어오는 곽회의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>11월 : 초국의 곽회부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>11월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 곽회의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>11월 : 서량성의 부대는 공격해 들어오는 장료의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>11월 : 초국의 장료부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>11월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 장료의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>10월 : 서량성의 부대는 공격해 들어오는 화핵의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>10월 : 초국의 화핵부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>10월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 화핵의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>6월 : 서량성의 부대는 공격해 들어오는 곽회의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>6월 : 초국의 곽회부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>6월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 곽회의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>6월 : 서량성의 부대는 공격해 들어오는 태사향의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>6월 : 초국의 태사향부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>6월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 태사향의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>4월 : 서량성의 부대는 공격해 들어오는 조민의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>4월 : 초국의 조민부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>4월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 조민의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#41A541>2월 : 장합의 부대가 하비성을 점령했다!</font>
<font color=#41A541>2월 : 촉국의 장합부대는 하비성에 쳐들어갔습니다!</font>
<font color=#41A541>2월 : 하비성의 수비대가 농성을 준비하고 있는 듯 하다! 장합의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>1월 : 서량성의 부대는 공격해 들어오는 곽사의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>1월 : 초국의 곽사부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>1월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 곽사의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>11월 : 서량성의 부대는 공격해 들어오는 태사향의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>11월 : 초국의 태사향부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>11월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 태사향의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#D064D0>9월 : 서량성의 부대는 공격해 들어오는 유봉의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#D064D0>9월 : 초국의 유봉부대는 서량성에 쳐들어갔습니다!</font>
<font color=#D064D0>9월 : 서량성의 수비대가 농성을 준비하고 있는 듯 하다! 유봉의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#41A541>9월 : 하비성의 부대는 공격해 들어오는 주환의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#41A541>9월 : 촉국의 주환부대는 하비성에 쳐들어갔습니다!</font>
<font color=#41A541>9월 : 하비성의 수비대가 농성을 준비하고 있는 듯 하다! 주환의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#FF9D6E>7월 : 비시의 부대가 허창성을 점령했다!</font>
<font color=#FF9D6E>7월 : 고구려국의 비시부대는 허창성에 쳐들어갔습니다!</font>
<font color=#FF9D6E>7월 : 허창성의 수비대가 농성을 준비하고 있는 듯 하다! 비시의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#FF9D6E>7월 : 허창성의 부대는 공격해 들어오는 황보숭의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#FF9D6E>7월 : 고구려국의 황보숭부대는 허창성에 쳐들어갔습니다!</font>
<font color=#FF9D6E>7월 : 허창성의 수비대가 농성을 준비하고 있는 듯 하다! 황보숭의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#FF9D6E>7월 : 허창성의 부대는 공격해 들어오는 평강의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#FF9D6E>7월 : 고구려국의 평강부대는 허창성에 쳐들어갔습니다!</font>
<font color=#FF9D6E>7월 : 허창성의 수비대가 농성을 준비하고 있는 듯 하다! 평강의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#FF9D6E>7월 : 허창성의 부대는 공격해 들어오는 마초의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#FF9D6E>7월 : 고구려국의 마초부대는 허창성에 쳐들어갔습니다!</font>
<font color=#FF9D6E>7월 : 허창성의 수비대가 농성을 준비하고 있는 듯 하다! 마초의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#41A541>7월 : 하비성의 부대는 공격해 들어오는 서성의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#41A541>7월 : 촉국의 서성부대는 하비성에 쳐들어갔습니다!</font>
<font color=#41A541>7월 : 하비성의 수비대가 농성을 준비하고 있는 듯 하다! 서성의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#8B8212>7월 : 왕윤의 부대는 공격해 들어오는 양만춘의 부대를 요격으로 전멸시킨 모양이다.</font>
<table border=1 width=274 align=center><tr><td width=100 bgcolor=#8B8212><p align=center><img src=./image/663.gif></p></td><td width=52 height=171 rowspan=3 bgcolor=black><p align=center><b><font color=white>VS</font></b></p></td><td width=100 bgcolor=#FF9D6E><p align=center><img src=./image/328.gif></p></td></tr><tr><td width=100 height=19 bgcolor=#8B8212><p align=center><b>양만춘<br></b></td><td width=100 height=19 bgcolor=#FF9D6E><p align=center><b>왕윤</b></td></tr><tr><td width=100 height=102 bgcolor=black><p><b>총전투력:37</b><br>병종:궁병<br>훈련도:100<br>지형상성:95</td><td width=100 height=102  bgcolor=black><b>총전투력:0</b><br>병종:보병<br>훈련도:100<br>지형상성:100</td></tr></table>
<font color=#8B8212>7월 : 신라국의 양만춘부대는 낙양성에 쳐들어갔습니다!</font>
<HR NOSHADE SIZE=3>
<font color=#FF9D6E>7월 : 허창성의 부대는 공격해 들어오는 양호의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#FF9D6E>7월 : 고구려국의 양호부대는 허창성에 쳐들어갔습니다!</font>
<font color=#FF9D6E>7월 : 허창성의 수비대가 농성을 준비하고 있는 듯 하다! 양호의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#FF9D6E>6월 : 대교의 부대가 홍농성을 점령했다!</font>
<font color=#FF9D6E>6월 : 고구려국의 대교부대는 홍농성에 쳐들어갔습니다!</font>
<font color=#FF9D6E>6월 : 홍농성의 수비대가 농성을 준비하고 있는 듯 하다! 대교의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#FF9D6E>6월 : 홍농성의 부대는 공격해 들어오는 고간의 부대를 요격으로 전멸시킨 모양이다.</font>
<font color=#FF9D6E>6월 : 고구려국의 고간부대는 홍농성에 쳐들어갔습니다!</font>
<font color=#FF9D6E>6월 : 홍농성의 수비대가 농성을 준비하고 있는 듯 하다! 고간의 부대는 성벽을 공격할 태세다!</font>
<HR NOSHADE SIZE=3>
<font color=#FF9D6E>6월 : 평강의 부대는 요격중이던 북두의 부대를 파죽지세로 전멸시킨 모양이다.</font>
<font color=#FF9D6E>6월 : 양쪽 군세에서 장수들이 나와 호통을 치기 시작했다!</font>
<table border=1 width=274 align=center><tr><td width=100 bgcolor=#FF9D6E><p align=center><img src=./image/666.gif></p></td><td width=52 height=171 rowspan=3 bgcolor=black><p align=center><b><font color=white>VS</font></b></p></td><td width=100 bgcolor=#8B8212><p align=center><img src=./image/167.gif></p></td></tr><tr><td width=100 height=19 bgcolor=#FF9D6E><p align=center><b>평강<br></b></td><td width=100 height=19 bgcolor=#8B8212><p align=center><b>북두</b></td></tr><tr><td width=100 height=102 bgcolor=black><p><b>총전투력:45</b><br>병종:궁병<br>훈련도:100<br>지형상성:95</td><td width=100 height=102  bgcolor=black><b>총전투력:36</b><br>병종:창병<br>훈련도:73<br>지형상성:90</td></tr></table>
<font color=#FF9D6E>6월 : 고구려국의 평강부대는 허창성에 쳐들어갔습니다!</font>
<HR NOSHADE SIZE=3>
